import { AlertTriangle, Clock, Calendar, Play, CheckCircle } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';

export const DueTraining = () => {
  const dueTraining = [
    {
      id: 1,
      title: 'Fire Safety Training',
      type: 'mandatory',
      dueDate: '2 days overdue',
      priority: 'urgent',
      progress: 0,
      status: 'not-started',
      description: 'Annual fire safety and evacuation procedures',
      estimatedTime: '45 minutes',
      autoGenerated: true
    },
    {
      id: 2,
      title: 'Customer Service Excellence',
      type: 'mandatory',
      dueDate: 'Due in 3 days',
      priority: 'high',
      progress: 75,
      status: 'in-progress',
      description: 'Advanced customer service techniques and conflict resolution',
      estimatedTime: '2 hours',
      autoGenerated: false
    },
    {
      id: 3,
      title: 'Data Protection & Privacy',
      type: 'mandatory',
      dueDate: 'Due in 1 week',
      priority: 'medium',
      progress: 0,
      status: 'not-started',
      description: 'GDPR compliance and data handling procedures',
      estimatedTime: '1 hour',
      autoGenerated: true
    },
    {
      id: 4,
      title: 'Health & Safety Update',
      type: 'mandatory',
      dueDate: 'Due in 2 weeks',
      priority: 'medium',
      progress: 25,
      status: 'in-progress',
      description: 'Updated workplace safety protocols and procedures',
      estimatedTime: '30 minutes',
      autoGenerated: true
    }
  ];

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'urgent': return 'bg-red-100 text-red-800 border-red-200';
      case 'high': return 'bg-orange-100 text-orange-800 border-orange-200';
      case 'medium': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      case 'low': return 'bg-green-100 text-green-800 border-green-200';
      default: return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'not-started': return <Play className="h-4 w-4" />;
      case 'in-progress': return <Clock className="h-4 w-4" />;
      case 'completed': return <CheckCircle className="h-4 w-4" />;
      default: return <Play className="h-4 w-4" />;
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <AlertTriangle className="h-5 w-5 text-red-500" />
          Due Training
          <Badge className="bg-red-100 text-red-800 ml-2">
            {dueTraining.filter(t => t.dueDate.includes('overdue')).length} Overdue
          </Badge>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {dueTraining.map((training) => (
            <div key={training.id} className={`p-4 rounded-lg border-2 ${
              training.dueDate.includes('overdue') ? 'bg-red-50 border-red-200' : 'bg-gray-50 border-gray-200'
            }`}>
              <div className="flex items-start justify-between mb-3">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <h4 className="font-medium text-gray-900">{training.title}</h4>
                    {training.autoGenerated && (
                      <Badge variant="default" className="text-xs">
                        Auto-generated
                      </Badge>
                    )}
                  </div>
                  <p className="text-sm text-gray-600 mb-2">{training.description}</p>
                  <div className="flex items-center gap-4 text-sm text-gray-500">
                    <div className="flex items-center gap-1">
                      <Calendar className="h-3 w-3" />
                      {training.dueDate}
                    </div>
                    <div className="flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      {training.estimatedTime}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {training.dueDate.includes('overdue') && (
                    <AlertTriangle className="h-4 w-4 text-red-500" />
                  )}
                  <Badge className={getPriorityColor(training.priority)}>
                    {training.priority}
                  </Badge>
                </div>
              </div>
              
              {training.progress > 0 && (
                <div className="space-y-2 mb-3">
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">Progress</span>
                    <span className="font-medium">{training.progress}%</span>
                  </div>
                  <Progress value={training.progress} className="h-2" />
                </div>
              )}
              
              <div className="flex justify-between items-center">
                <Badge variant="default" className="flex items-center gap-1">
                  {getStatusIcon(training.status)}
                  <span className="capitalize">{training.status.replace('-', ' ')}</span>
                </Badge>
                <Button size="sm" className={
                  training.dueDate.includes('overdue') 
                    ? 'bg-red-600 hover:bg-red-700 text-white' 
                    : training.priority === 'high' 
                    ? 'bg-orange-600 hover:bg-orange-700 text-white'
                    : 'bg-white'
                }>
                  {training.status === 'not-started' ? 'Start Training' : 'Continue'}
                </Button>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};